export const employeeDetails = {
    FetchAdminMasters: "FetchAdminMasters?Type=6&Filter=Blocked=0&USERID=${UserID}&WORKSTATIONID=${WorkStationID}&HospitalID=${HospitalID}",
    FetchEmployeeMasters: "FetchEmployeeMasters?UserID=${UserID}&WorkStationID=${WorkStationID}&HospitalID=${HospitalID}",
    FetchEmployeeLocation: "FetchEmployeeLocation?UserID=${UserID}&WorkStationID=${WorkStationID}&HospitalID=${HospitalID}",
    FetchEmployeeTitleGender: "FetchEmployeeTitleGender?TitleID=${TitleID}&UserID=${UserID}&WorkStationID=${WorkStationID}&HospitalID=${HospitalID}",
    FetchEmployeeDepartments: "FetchEmployeeDepartments?HospitalID=${HospitalID}&UserID=${UserID}&WorkStationID=${WorkStationID}&SelectedHospitalID=${SelectedHospitalID}",
    FetchEmployeeDesignation: "FetchEmployeeDesignation?HospitalID=${HospitalID}&UserID=${UserID}&WorkStationID=${WorkStationID}&DepartmentID=${DepartmentID}",
    FetchReligions: "FetchReligions?UserID=${UserID}&WorkStationID=${WorkStationID}&HospitalID=${HospitalID}",
    FetchAdmRoutes: "FetchAdmRoutes?Type=${Type}&DisplayName=${DisplayName}",
    FetchGDomain: "FetchGDomain?Type=2&DisplayName=${DisplayName}&HospitalID=${HospitalID}",
    SaveEmployee: "SaveEmployeeUser",
    UpdateEmployee: "SaveEmployeeUser",
    FetchPlaces: "FetchPlaces?city=${city}&UserId=${UserId}&WorkStationID=${WorkStationID}&HospitalID=${HospitalID}",
    FetchSSEmployees: "FetchSSEmployees?name=${name}&UserId=${UserId}&WorkStationID=${WorkStationID}&HospitalID=${HospitalID}",
    FetchSSEmployeesE: "FetchSSEmployeesE?name=${name}&UserId=${UserId}&WorkStationID=${WorkStationID}&HospitalID=${HospitalID}",
    FetchEmployee: "FetchEmployee?EmpId=${EmpId}&UserId=${UserId}&WorkStationID=${WorkStationID}&HospitalID=${HospitalID}",
    BlockEmployee: "BlockEmployee",
    FetchHospitalLocations:'FetchHospitalLocations?type=0&filter=blocked=0&UserId=0&WorkstationId=0',
    SaveEmployeeHospitals:'SaveEmployeeHospitals',
    FetchEmployeeHospitals:'FetchEmployeeHospitals?EmpID=${EmpID}&UserID=${UserID}&WorkStationID=${WorkStationID}&HospitalID=${HospitalID}',
    SaveEmployeeSignatures:'SaveEmployeeSignatures',
    FetchEmploymentRoleNames: "FetchEmploymentRoleNames?WorkStationID=${WorkStationID}&HospitalID=${HospitalID}",
    SickleaveVerifyDoctor:'SickleaveVerifyDoctor',
    UpdateEmployeeSehaVerified:"UpdateEmployeeSehaVerified"
};